export type { PrimitiveAProps as AProps } from './primitive-a';
export type { PrimitiveAbbrProps as AbbrProps } from './primitive-abbr';
export type { PrimitiveAddressProps as AddressProps } from './primitive-address';
export type { PrimitiveAreaProps as AreaProps } from './primitive-area';
export type { PrimitiveArticleProps as ArticleProps } from './primitive-article';
export type { PrimitiveAsideProps as AsideProps } from './primitive-aside';
export type { PrimitiveAudioProps as AudioProps } from './primitive-audio';
export type { PrimitiveBProps as BProps } from './primitive-b';
export type { PrimitiveBdiProps as BdiProps } from './primitive-bdi';
export type { PrimitiveBdoProps as BdoProps } from './primitive-bdo';
export type { PrimitiveBlockquoteProps as BlockquoteProps } from './primitive-blockquote';
export type { PrimitiveBrProps as BrProps } from './primitive-br';
export type { PrimitiveButtonProps as ButtonProps } from './primitive-button';
export type { PrimitiveCanvasProps as CanvasProps } from './primitive-canvas';
export type { PrimitiveCaptionProps as CaptionProps } from './primitive-caption';
export type { PrimitiveCiteProps as CiteProps } from './primitive-cite';
export type { PrimitiveCodeProps as CodeProps } from './primitive-code';
export type { PrimitiveColProps as ColProps } from './primitive-col';
export type { PrimitiveColgroupProps as ColgroupProps } from './primitive-colgroup';
export type { PrimitiveDataProps as DataProps } from './primitive-data';
export type { PrimitiveDatalistProps as DatalistProps } from './primitive-datalist';
export type { PrimitiveDdProps as DdProps } from './primitive-dd';
export type { PrimitiveDelProps as DelProps } from './primitive-del';
export type { PrimitiveDetailsProps as DetailsProps } from './primitive-details';
export type { PrimitiveDfnProps as DfnProps } from './primitive-dfn';
export type { PrimitiveDialogProps as DialogProps } from './primitive-dialog';
export type { PrimitiveDivProps as DivProps } from './primitive-div';
export type { PrimitiveDlProps as DlProps } from './primitive-dl';
export type { PrimitiveDtProps as DtProps } from './primitive-dt';
export type { PrimitiveEmProps as EmProps } from './primitive-em';
export type { PrimitiveEmbedProps as EmbedProps } from './primitive-embed';
export type { PrimitiveFieldsetProps as FieldsetProps } from './primitive-fieldset';
export type { PrimitiveFigcaptionProps as FigcaptionProps } from './primitive-figcaption';
export type { PrimitiveFigureProps as FigureProps } from './primitive-figure';
export type { PrimitiveFooterProps as FooterProps } from './primitive-footer';
export type { PrimitiveFormProps as FormProps } from './primitive-form';
export type { PrimitiveH1Props as H1Props } from './primitive-h1';
export type { PrimitiveH2Props as H2Props } from './primitive-h2';
export type { PrimitiveH3Props as H3Props } from './primitive-h3';
export type { PrimitiveH4Props as H4Props } from './primitive-h4';
export type { PrimitiveH5Props as H5Props } from './primitive-h5';
export type { PrimitiveH6Props as H6Props } from './primitive-h6';
export type { PrimitiveHeaderProps as HeaderProps } from './primitive-header';
export type { PrimitiveHgroupProps as HgroupProps } from './primitive-hgroup';
export type { PrimitiveHrProps as HrProps } from './primitive-hr';
export type { PrimitiveIProps as IProps } from './primitive-i';
export type { PrimitiveIframeProps as IframeProps } from './primitive-iframe';
export type { PrimitiveImgProps as ImgProps } from './primitive-img';
export type { PrimitiveInsProps as InsProps } from './primitive-ins';
export type { PrimitiveKbdProps as KbdProps } from './primitive-kbd';
export type { PrimitiveLabelProps as LabelProps } from './primitive-label';
export type { PrimitiveLegendProps as LegendProps } from './primitive-legend';
export type { PrimitiveLiProps as LiProps } from './primitive-li';
export type { PrimitiveMainProps as MainProps } from './primitive-main';
export type { PrimitiveMapProps as MapProps } from './primitive-map';
export type { PrimitiveMarkProps as MarkProps } from './primitive-mark';
export type { PrimitiveMenuProps as MenuProps } from './primitive-menu';
export type { PrimitiveMeterProps as MeterProps } from './primitive-meter';
export type { PrimitiveNavProps as NavProps } from './primitive-nav';
export type { PrimitiveNoscriptProps as NoscriptProps } from './primitive-noscript';
export type { PrimitiveObjectProps as ObjectProps } from './primitive-object';
export type { PrimitiveOlProps as OlProps } from './primitive-ol';
export type { PrimitiveOptgroupProps as OptgroupProps } from './primitive-optgroup';
export type { PrimitiveOutputProps as OutputProps } from './primitive-output';
export type { PrimitivePProps as PProps } from './primitive-p';
export type { PrimitivePictureProps as PictureProps } from './primitive-picture';
export type { PrimitivePreProps as PreProps } from './primitive-pre';
export type { PrimitiveProgressProps as ProgressProps } from './primitive-progress';
export type { PrimitiveQProps as QProps } from './primitive-q';
export type { PrimitiveRpProps as RpProps } from './primitive-rp';
export type { PrimitiveRtProps as RtProps } from './primitive-rt';
export type { PrimitiveRubyProps as RubyProps } from './primitive-ruby';
export type { PrimitiveSProps as SProps } from './primitive-s';
export type { PrimitiveSampProps as SampProps } from './primitive-samp';
export type { PrimitiveScriptProps as ScriptProps } from './primitive-script';
export type { PrimitiveSearchProps as SearchProps } from './primitive-search';
export type { PrimitiveSectionProps as SectionProps } from './primitive-section';
export type { PrimitiveSelectProps as SelectProps } from './primitive-select';
export type { PrimitiveSmallProps as SmallProps } from './primitive-small';
export type { PrimitiveSourceProps as SourceProps } from './primitive-source';
export type { PrimitiveSpanProps as SpanProps } from './primitive-span';
export type { PrimitiveStrongProps as StrongProps } from './primitive-strong';
export type { PrimitiveSubProps as SubProps } from './primitive-sub';
export type { PrimitiveSummaryProps as SummaryProps } from './primitive-summary';
export type { PrimitiveSupProps as SupProps } from './primitive-sup';
export type { PrimitiveSvgProps as SvgProps } from './primitive-svg';
export type { PrimitiveTableProps as TableProps } from './primitive-table';
export type { PrimitiveTbodyProps as TbodyProps } from './primitive-tbody';
export type { PrimitiveTdProps as TdProps } from './primitive-td';
export type { PrimitiveTextareaProps as TextareaProps } from './primitive-textarea';
export type { PrimitiveTfootProps as TfootProps } from './primitive-tfoot';
export type { PrimitiveThProps as ThProps } from './primitive-th';
export type { PrimitiveTheadProps as TheadProps } from './primitive-thead';
export type { PrimitiveTimeProps as TimeProps } from './primitive-time';
export type { PrimitiveTrProps as TrProps } from './primitive-tr';
export type { PrimitiveTrackProps as TrackProps } from './primitive-track';
export type { PrimitiveUProps as UProps } from './primitive-u';
export type { PrimitiveUlProps as UlProps } from './primitive-ul';
export type { PrimitiveVarProps as VarProps } from './primitive-var';
export type { PrimitiveVideoProps as VideoProps } from './primitive-video';
export type { PrimitiveWbrProps as WbrProps } from './primitive-wbr';

export { PrimitiveA as a } from './primitive-a';
export { PrimitiveAbbr as abbr } from './primitive-abbr';
export { PrimitiveAddress as address } from './primitive-address';
export { PrimitiveArea as area } from './primitive-area';
export { PrimitiveArticle as article } from './primitive-article';
export { PrimitiveAside as aside } from './primitive-aside';
export { PrimitiveAudio as audio } from './primitive-audio';
export { PrimitiveB as b } from './primitive-b';
export { PrimitiveBdi as bdi } from './primitive-bdi';
export { PrimitiveBdo as bdo } from './primitive-bdo';
export { PrimitiveBlockquote as blockquote } from './primitive-blockquote';
export { PrimitiveBr as br } from './primitive-br';
export { PrimitiveButton as button } from './primitive-button';
export { PrimitiveCanvas as canvas } from './primitive-canvas';
export { PrimitiveCaption as caption } from './primitive-caption';
export { PrimitiveCite as cite } from './primitive-cite';
export { PrimitiveCode as code } from './primitive-code';
export { PrimitiveCol as col } from './primitive-col';
export { PrimitiveColgroup as colgroup } from './primitive-colgroup';
export { PrimitiveData as data } from './primitive-data';
export { PrimitiveDatalist as datalist } from './primitive-datalist';
export { PrimitiveDd as dd } from './primitive-dd';
export { PrimitiveDel as del } from './primitive-del';
export { PrimitiveDetails as details } from './primitive-details';
export { PrimitiveDfn as dfn } from './primitive-dfn';
export { PrimitiveDialog as dialog } from './primitive-dialog';
export { PrimitiveDiv as div } from './primitive-div';
export { PrimitiveDl as dl } from './primitive-dl';
export { PrimitiveDt as dt } from './primitive-dt';
export { PrimitiveEm as em } from './primitive-em';
export { PrimitiveEmbed as embed } from './primitive-embed';
export { PrimitiveFieldset as fieldset } from './primitive-fieldset';
export { PrimitiveFigcaption as figcaption } from './primitive-figcaption';
export { PrimitiveFigure as figure } from './primitive-figure';
export { PrimitiveFooter as footer } from './primitive-footer';
export { PrimitiveForm as form } from './primitive-form';
export { PrimitiveH1 as h1 } from './primitive-h1';
export { PrimitiveH2 as h2 } from './primitive-h2';
export { PrimitiveH3 as h3 } from './primitive-h3';
export { PrimitiveH4 as h4 } from './primitive-h4';
export { PrimitiveH5 as h5 } from './primitive-h5';
export { PrimitiveH6 as h6 } from './primitive-h6';
export { PrimitiveHeader as header } from './primitive-header';
export { PrimitiveHgroup as hgroup } from './primitive-hgroup';
export { PrimitiveHr as hr } from './primitive-hr';
export { PrimitiveI as i } from './primitive-i';
export { PrimitiveIframe as iframe } from './primitive-iframe';
export { PrimitiveImg as img } from './primitive-img';
export { PrimitiveIns as ins } from './primitive-ins';
export { PrimitiveKbd as kbd } from './primitive-kbd';
export { PrimitiveLabel as label } from './primitive-label';
export { PrimitiveLegend as legend } from './primitive-legend';
export { PrimitiveLi as li } from './primitive-li';
export { PrimitiveMain as main } from './primitive-main';
export { PrimitiveMap as map } from './primitive-map';
export { PrimitiveMark as mark } from './primitive-mark';
export { PrimitiveMenu as menu } from './primitive-menu';
export { PrimitiveMeter as meter } from './primitive-meter';
export { PrimitiveNav as nav } from './primitive-nav';
export { PrimitiveNoscript as noscript } from './primitive-noscript';
export { PrimitiveObject as object } from './primitive-object';
export { PrimitiveOl as ol } from './primitive-ol';
export { PrimitiveOptgroup as optgroup } from './primitive-optgroup';
export { PrimitiveOutput as output } from './primitive-output';
export { PrimitiveP as p } from './primitive-p';
export { PrimitivePicture as picture } from './primitive-picture';
export { PrimitivePre as pre } from './primitive-pre';
export { PrimitiveProgress as progress } from './primitive-progress';
export { PrimitiveQ as q } from './primitive-q';
export { PrimitiveRp as rp } from './primitive-rp';
export { PrimitiveRt as rt } from './primitive-rt';
export { PrimitiveRuby as ruby } from './primitive-ruby';
export { PrimitiveS as s } from './primitive-s';
export { PrimitiveSamp as samp } from './primitive-samp';
export { PrimitiveScript as script } from './primitive-script';
export { PrimitiveSearch as search } from './primitive-search';
export { PrimitiveSection as section } from './primitive-section';
export { PrimitiveSelect as select } from './primitive-select';
export { PrimitiveSmall as small } from './primitive-small';
export { PrimitiveSource as source } from './primitive-source';
export { PrimitiveSpan as span } from './primitive-span';
export { PrimitiveStrong as strong } from './primitive-strong';
export { PrimitiveSub as sub } from './primitive-sub';
export { PrimitiveSummary as summary } from './primitive-summary';
export { PrimitiveSup as sup } from './primitive-sup';
export { PrimitiveSvg as svg } from './primitive-svg';
export { PrimitiveTable as table } from './primitive-table';
export { PrimitiveTbody as tbody } from './primitive-tbody';
export { PrimitiveTd as td } from './primitive-td';
export { PrimitiveTextarea as textarea } from './primitive-textarea';
export { PrimitiveTfoot as tfoot } from './primitive-tfoot';
export { PrimitiveTh as th } from './primitive-th';
export { PrimitiveThead as thead } from './primitive-thead';
export { PrimitiveTime as time } from './primitive-time';
export { PrimitiveTr as tr } from './primitive-tr';
export { PrimitiveTrack as track } from './primitive-track';
export { PrimitiveU as u } from './primitive-u';
export { PrimitiveUl as ul } from './primitive-ul';
export { PrimitiveVar as var } from './primitive-var';
export { PrimitiveVideo as video } from './primitive-video';
export { PrimitiveWbr as wbr } from './primitive-wbr';
