export { TableRoot as Root } from './table-root';
export { TableContent as Content } from './table-content';
export { TableCaption as Caption } from './table-caption';
export { TableHeader as Header } from './table-header';
export { TableBody as Body } from './table-body';
export { TableRow as Row } from './table-row';
export { TableCell as Cell } from './table-cell';
export { TableColumnHeaderCell as ColumnHeaderCell } from './table-column-header-cell';
export { TableRowHeaderCell as RowHeaderCell } from './table-row-header-cell';
